manifest:
  remotes:
    - name: lora-net
      url-base: https://github.com/lora-net
  
  projects:
    - name: LBM_Zephyr
      path: modules/LBM_Zephyr
      remote: lora-net
      repo-path: LBM_Zephyr
      revision: main
      import: true
