name: Run Bringup Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          path: t-watch-s3
      
      - name: Setup and Activate Python Environment
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
          pip install west

      - name: Initialize Project
        run: |
          west init -l
          west update

      - name: Install Dependencies
        run: |
          west zephyr-export
          west packages pip --install

      - name: Fetch Espressif Blobs
        run: |
          west blobs fetch hal_espressif

      - name: Run Twister Tests
        run: >
          west twister 
            --device-testing 
            --device-serial /dev/ttyACM0 
            -p t_watch_s3/esp32s3/procpu 
            -T t-watch-s3
            --flash-before
